### ISSUE TITLE
Balance Screen: Error Displaying the balance; showing NaN PKR on some accounts

### ISSUE THREAD

**Issue by isabeen** [aqibbangash/ajoor-project#106]
![cats](https://user-images.githubusercontent.com/53593496/64014991-f6c39580-cb3c-11e9-9e02-2b511f3dd7ab.jpg)

**Comment by sheerazanwar** [comment]
@isabeen Can you please mention that account?
So that i can check this issue.

**Comment by isabeen** [comment]
@sheerazanwar  mohsinabid901@gmail.com
