### ISSUE TITLE
Withdraw balance: when balance is 0 or no bank card is added -> add a dialog "Not enough balance" instead of going to next screen.

### ISSUE THREAD

**Issue by isabeen** [aqibbangash/ajoor-project#108]
See the picture for reference: 
https://user-images.githubusercontent.com/53593496/63688228-3712d300-c820-11e9-82df-1d30d8e72f4f.jpg

**Comment by UsmanTahir101** [comment]
Done

**Comment by isabeen** [comment]
@UsmanTahir101 Not done for balance 0.0

**Comment by UsmanTahir101** [comment]
Done
