### ISSUE TITLE
'Payment Receiver' Tag is wrong; in both months the tag is for the same user. (Check with Android). See details below. 

### ISSUE THREAD

**Issue by isabeen** [aqibbangash/ajoor-project#136]
Note: Issue only occurs for plan type: Weekly
**Account used:** 
mohsinabid901@gmail.com
123

**Scheme Details:**
Name: 4th Sept Web
2nd user:  
khannssabeen@gmail.com 
123 

![WhatsApp Image 2019-09-04 at 2 53 50 PM](https://user-images.githubusercontent.com/53593496/64245474-6a421a00-cf24-11e9-80e0-8e45051ae33b.jpeg)

**Comment by UsmanTahir101** [comment]
Done
