### ISSUE TITLE
Design Implementations - Static

### ISSUE THREAD

**Issue by aqibbangash** [aqibbangash/ajoor-project#6]
Complete UI Implementation needs to be carried out.
Incase of Dynamic elements like Tables, Lists, Collections e.t.c, you need to make sure that you have generated the Base Table or List Cells properly. You may keep the value dummy.
Designs will be attached here shortly.

**Comment by aqibbangash** [comment]
Designs Attached Below
@UsmanTahir101 @mohsinabid 

![1_splash screen](https://user-images.githubusercontent.com/8043091/51836541-88a6be00-2322-11e9-977a-a5a8ea64a09d.jpg)
![2_log in](https://user-images.githubusercontent.com/8043091/51836542-88a6be00-2322-11e9-9669-ba1aa2ed5ff5.jpg)
![4_sign up](https://user-images.githubusercontent.com/8043091/51836543-893f5480-2322-11e9-8cb5-e356e9ec3d6e.jpg)
![5_home](https://user-images.githubusercontent.com/8043091/51836544-893f5480-2322-11e9-9053-f3c69c03c6e7.jpg)
![6_current scheme details](https://user-images.githubusercontent.com/8043091/51836545-893f5480-2322-11e9-93c7-307bd124595e.jpg)
![6_forgot password](https://user-images.githubusercontent.com/8043091/51836546-89d7eb00-2322-11e9-83a2-e3957acb8823.jpg)
![7_current scheme details- participants list](https://user-images.githubusercontent.com/8043091/51836549-89d7eb00-2322-11e9-8e2b-091f9e2dcc04.jpg)
![8_notifications](https://user-images.githubusercontent.com/8043091/51836550-89d7eb00-2322-11e9-9977-68e530a0ca96.jpg)
![9_more options](https://user-images.githubusercontent.com/8043091/51836551-8a708180-2322-11e9-876b-48aab9a8d4e1.jpg)
![10_add scheme](https://user-images.githubusercontent.com/8043091/51836552-8a708180-2322-11e9-8f01-f6913993335f.jpg)
![11 add_scheme_enter information](https://user-images.githubusercontent.com/8043091/51836554-8a708180-2322-11e9-94e2-f978dfc02fd0.jpg)
![12 add_scheme_entered information](https://user-images.githubusercontent.com/8043091/51836555-8b091800-2322-11e9-90a8-148a54ef67de.jpg)
![13 add_scheme_participants](https://user-images.githubusercontent.com/8043091/51836556-8b091800-2322-11e9-93bf-2956a0c7ef21.jpg)
![14 add_scheme_add participants](https://user-images.githubusercontent.com/8043091/51836557-8b091800-2322-11e9-8c9f-67a70d3ed36c.jpg)
![15 add_scheme_participant added](https://user-images.githubusercontent.com/8043091/51836558-8b091800-2322-11e9-999a-6a89c26a955b.jpg)
![16 add_scheme_serach_invite](https://user-images.githubusercontent.com/8043091/51836559-8ba1ae80-2322-11e9-8dde-f8f52fee1dc3.jpg)
![17 add_scheme_pyment_schedule](https://user-images.githubusercontent.com/8043091/51836560-8ba1ae80-2322-11e9-8f99-912f0a6c61f7.jpg)
![18 add_scheme_beneficiary_list](https://user-images.githubusercontent.com/8043091/51836561-8ba1ae80-2322-11e9-9bd0-886ea98ccd92.jpg)
![19_more options_ivited scheme](https://user-images.githubusercontent.com/8043091/51836562-8c3a4500-2322-11e9-91c5-b68581a32ad3.jpg)
![20_more options_ivited schemes_details](https://user-images.githubusercontent.com/8043091/51836563-8c3a4500-2322-11e9-826f-4f1d19ecf089.jpg)
![21_more options_invited_schemes_participants](https://user-images.githubusercontent.com/8043091/51836564-8c3a4500-2322-11e9-976d-fe3b18e6b4bb.jpg)
![22_more options_my schemes](https://user-images.githubusercontent.com/8043091/51836566-8cd2db80-2322-11e9-9bb5-48107cf7a8f2.jpg)
![23_my schemes_scheme details](https://user-images.githubusercontent.com/8043091/51836567-8cd2db80-2322-11e9-9b46-813120caae3c.jpg)
![24_my schemes_scheme details_participants](https://user-images.githubusercontent.com/8043091/51836568-8cd2db80-2322-11e9-9ade-2cda0a3ff05d.jpg)
![25_my schemes_edit](https://user-images.githubusercontent.com/8043091/51836569-8d6b7200-2322-11e9-8a01-85282a74da17.jpg)
![26 1_my schemes_payment_payment schedule 2](https://user-images.githubusercontent.com/8043091/51836571-8d6b7200-2322-11e9-8094-0e9f247783cb.jpg)
![26 1_my schemes_payment_payment schedule 3](https://user-images.githubusercontent.com/8043091/51836572-8d6b7200-2322-11e9-935a-27e9a37c6405.jpg)
![26 1_my schemes_payment_payment schedule 4](https://user-images.githubusercontent.com/8043091/51836573-8e040880-2322-11e9-8521-4421676c4c10.jpg)
![26 1_my schemes_payment_payment schedule 5](https://user-images.githubusercontent.com/8043091/51836574-8e040880-2322-11e9-9c7b-3b4b13c271b3.jpg)
![26 1_my schemes_payment_payment schedule weekly](https://user-images.githubusercontent.com/8043091/51836575-8e040880-2322-11e9-86ca-dd6304beeaf2.jpg)
![28_my schemes_payment_beneficiary list 2](https://user-images.githubusercontent.com/8043091/51836576-8e040880-2322-11e9-9a13-d268ce421009.jpg)
![28_my schemes_payment_beneficiary list weekly](https://user-images.githubusercontent.com/8043091/51836577-8e9c9f00-2322-11e9-9e60-a84f99f0768b.jpg)
![29_more options_balance _ deposits1](https://user-images.githubusercontent.com/8043091/51836578-8e9c9f00-2322-11e9-9c24-1707a965bdea.jpg)
![29_more options_balance- withdraw](https://user-images.githubusercontent.com/8043091/51836579-8e9c9f00-2322-11e9-9fe2-b8382e97ff89.jpg)
![30_more options_balance_withdraw 1](https://user-images.githubusercontent.com/8043091/51836580-8f353580-2322-11e9-8113-9843f087be51.jpg)
![31_more options_balance_withdraw 1](https://user-images.githubusercontent.com/8043091/51836581-8f353580-2322-11e9-99ba-6b89d190fc67.jpg)
![32_more options_old schemes](https://user-images.githubusercontent.com/8043091/51836582-8f353580-2322-11e9-98ea-7046fb812a46.jpg)

**Comment by aqibbangash** [comment]
Screen-flows will be shared shortly.

**Comment by UsmanTahir101** [comment]
Please provide assets @aqibbangash  @maryam-awan

**Comment by maryam-awan** [comment]
[Ajoor_IoS (xd).zip](https://github.com/aqibbangash/ajoor-project/files/2806888/Ajoor_IoS.xd.zip)

**Comment by maryam-awan** [comment]
Design assets attached @UsmanTahir101 @mohsinabid

**Comment by UsmanTahir101** [comment]
@maryam-awan above file is incorrect please provide correct assets file.

**Comment by maryam-awan** [comment]
[Assets.zip](https://github.com/aqibbangash/ajoor-project/files/2807554/Assets.zip)

**Comment by maryam-awan** [comment]
assets attached @UsmanTahir101  @mohsinabid

**Comment by maryam-awan** [comment]
Mockups:
[Ajoor_Mockups.zip](https://github.com/aqibbangash/ajoor-project/files/2811779/Ajoor_Mockups.zip)

**Comment by maryam-awan** [comment]
Prototype: 
@mohsinabid  @UsmanTahir101  
https://xd.adobe.com/view/ee5fdcb6-90de-47f3-569f-929902078dcc-986e/?fullscreen

**Comment by maryam-awan** [comment]
iOS App icon 
[gotham-rounded.zip](https://github.com/aqibbangash/ajoor-project/files/2821275/gotham-rounded.zip)

**Comment by maryam-awan** [comment]
1024X1024 image  @UsmanTahir101
![untitled-2](https://user-images.githubusercontent.com/40426826/52119397-c6fdef00-263a-11e9-9dac-157f4795ca81.png)

**Comment by maryam-awan** [comment]
@UsmanTahir101 app icon attached
[ios.zip](https://github.com/aqibbangash/ajoor-project/files/2821299/ios.zip)

**Comment by maryam-awan** [comment]
@mohsinabid app icon attached
[android.zip](https://github.com/aqibbangash/ajoor-project/files/2821301/android.zip)

**Comment by maryam-awan** [comment]
Font: Gotham Rounded  @UsmanTahir101 @mohsinabid 

[gotham-rounded.zip](https://github.com/aqibbangash/ajoor-project/files/2821360/gotham-rounded.zip)

**Comment by aqibbangash** [comment]
@maryam-awan @mohsinabid @UsmanTahir101 
Design Variations

**Home Screen**
1. Participants goes in-front of Scheme Name.
2. Start - End goes in one line
3. Created By goes on one line with Amount.
4. All Schemes (Invited-Grey, Created-white, Participation-green)
5. View More Arrow goes to Right
6. Arrow only without circle
7. Description 1 line fixed
8. All item clickable

**Comment by maryam-awan** [comment]
Use these font color: @UsmanTahir101  @mohsinabid 
gray : #DCDCDC (invites)
green : #90EE90 (Participation)
top bar: #522F91
buttons: #270F4D
participants bar: #7165CB
text color: #7165CB where its purple
