### ISSUE TITLE
‘Manage Payment’ Screen: Descriptive text’s color inconsistency between both tabs (i.e. Deposit Details and Withdrawal Details)

### ISSUE THREAD

**Issue by isabeen** [aqibbangash/ajoor-project#70]
Also make sure that the size of the Title bar and text size in both tab's screens is same.

![cats](https://user-images.githubusercontent.com/53593496/63688811-cec4f100-c821-11e9-90bc-0d9225cc5387.jpg)

**Comment by UsmanTahir101** [comment]
Done
