### ISSUE TITLE
Via Notifications Section: Gives option to accept an already accepted scheme. (See Details)

### ISSUE THREAD

**Issue by isabeen** [aqibbangash/ajoor-project#75]
When an already accepted scheme is accepted again via notifications: The dialog says ‘Your invitation might be cancelled by the owner’ instead of saying ‘You have already accepted the scheme’ or 'could out perform action' e.t.c

**Note: iOS does not show 'accept/reject' option if a scheme is accepted already.**

![MicrosoftTeams-image](https://user-images.githubusercontent.com/53593496/63742591-b8b34100-c8b2-11e9-8105-9ab566060a7d.png)

**Comment by mohsinabid** [comment]
Done
