### ISSUE TITLE
Data Loading Issue on Back Arrow press from Scheme Details Screen to (My Schemes/Participated Schemes e.t.c)...See Video

### ISSUE THREAD

**Issue by isabeen** [aqibbangash/ajoor-project#77]
Menu: (My Schemes/Participated Schemes/Invited Schemes) -> Scheme Details -> ‘Back arrow’: **No loading dialog** and sometimes **no data is shown when returning back to schemes’ screen.** (See Video)

Video: https://we.tl/t-4u99lG6k9R

**Comment by UsmanTahir101** [comment]
Done
