### ISSUE TITLE
Currency should be written in Abbreviations i.e. USD instead of American Dollor (also spelling error of Dollar)

### ISSUE THREAD

**Issue by isabeen** [aqibbangash/ajoor-project#79]
![j](https://user-images.githubusercontent.com/53593496/63748263-742fa180-c8c2-11e9-9599-e2ef82da99ad.jpg)

**Comment by mohsinabid** [comment]
Done

**Comment by isabeen** [comment]
> Done
@mohsinabid 
Can you do the same for 'Sign up' screen?

**Comment by mohsinabid** [comment]
@isabeen Yes

**Comment by mohsinabid** [comment]
Done
