### ISSUE TITLE
Notifications are not sorted properly i.e. the latest notification does not appear at the start/bottom of the notification list

### ISSUE THREAD

**Issue by isabeen** [aqibbangash/ajoor-project#81]
![h](https://user-images.githubusercontent.com/53593496/63757132-063fa600-c8d3-11e9-987c-2e796b4abbe2.jpg)

**Comment by sheerazanwar** [comment]
Notifications are being sorted on the base of creation date. 
I have tested this issue with

email : mohsinabid901@gmail.com
password : 123

and all notifications are sorted properly.
Database screenshot is attached, You can check by logging in with above given account.
![Screenshot 2019-09-03 at 10 57 46 AM](https://user-images.githubusercontent.com/26300643/64147519-faeffb80-ce39-11e9-8d7d-cb0c56b4cdfa.png)

**Comment by sheerazanwar** [comment]
@maryam-awan @isabeen I have mentioned in above comment that this issue doesn't exist in actual from backend. I see no reason to label this issue as **wontfix**.

**Comment by isabeen** [comment]
> @maryam-awan @isabeen I have mentioned in above comment that this issue doesn't exist in actual from backend. I see no reason to label this issue as **wontfix**.

@sheerazanwar  wontfix means that the issue is invalid. (it won't be worked on, for now, so i'll check is later)
