### ISSUE TITLE
'Scheme Details' Screen: Often shows wrong information on different platforms (android and iOS)

### ISSUE THREAD

**Issue by isabeen** [aqibbangash/ajoor-project#85]
**Testing date: 26 and 27th Aug** 
- Made a Scheme using iOS named **'iOS Test'** and set the start date to be **1st September** 
- When viewed on android the start date shown was **31st Aug** and allowed user to make payments in Aug, however the start date was 1st sept.
- Payment history shows that payments are made on 1st Sept which is impossible.

**See the screenshots:**
![cats](https://user-images.githubusercontent.com/53593496/63765356-42c6ce00-c8e2-11e9-9465-22ce169cd402.jpg)

![s](https://user-images.githubusercontent.com/53593496/63765427-6ab63180-c8e2-11e9-9fdf-8d0e90a16d01.jpg)

**Comment by isabeen** [comment]
![c](https://user-images.githubusercontent.com/53593496/63831740-c2a77380-c988-11e9-9aa9-48ad4c4c1b35.jpg)

**Comment by mohsinabid** [comment]
Date issue is resolved

**Comment by UsmanTahir101** [comment]
Done
